### ISSUE TITLE
Dashboard > Wrap Top 5 Project Deployment Rewards' headers

### ISSUE THREAD

**Issue by Danielvul** [HuberTRoy/SubQuery-Scanner#20]
Currently the Dashboard's Top 5 Project Deployment Rewards table doesn't fit in a small monitor without horizontal scrolling

<img width="1423" alt="Screenshot 2024-10-29 at 1 30 00 PM" src="https://github.com/user-attachments/assets/13e05525-caed-4aad-949d-29851da2d954">

Reproduction Steps:
13" MacBook pro
Safari
https://sqtscan.com/dashboard

Expected:
Wrap the table headers like in the Project Deployments table
<img width="1414" alt="Screenshot 2024-10-29 at 1 27 54 PM" src="https://github.com/user-attachments/assets/2d05191d-a7a8-4906-a196-a98f40de0531">
https://sqtscan.com/deployments

**Comment by HuberTRoy** [comment]
https://github.com/HuberTRoy/subquery-sqtscan/pull/25

The horizontal scrolling bar is hidden by default on Mac, but the feature still effective. 

The PR also changed it to wrap in small screen.
