### ISSUE TITLE
Project Rewards | Remove Era Select filter

### ISSUE THREAD

**Issue by Danielvul** [HuberTRoy/SubQuery-Scanner#21]
I suggest removing the Era selector for the Projected Rewards calculator. 

**Reasoning:**
- There is little value in being able to estimate rewards based on old eras, when conditions have changed since then and will impact the rewards.
- Having an era selector adds confusion and complexity
- The projection logic could change in the future and might not always be based on a single Era

<img width="1052" alt="Screenshot 2024-10-29 at 1 52 46 PM" src="https://github.com/user-attachments/assets/6f26fd3a-6892-4c49-bcf0-52746e532231">

**Suggestion**
1. Remove the Previous Era selector in Project Rewards calculator
2. Update the description to "This provides an estimate of potential rewards based on historic data of the previous Era. Conditions change between Eras, this estimate is not a guarantee for future Eras."

**Comment by HuberTRoy** [comment]
https://github.com/HuberTRoy/subquery-sqtscan/pull/25
